//@version=2
//Supertrend Strategy by breizh29 using *rajandran.r* Supertrend Indicator
 strategy("Super Trend 2 Strategy", overlay=true, pyramiding = 0, default_qty_type = strategy.cash, currency = currency.USD)
 
res = input(title="Main SuperTrend Time Frame", type=resolution, defval="120")
Factor=input(1, minval=1,maxval = 100)
Pd=input(1, minval=1,maxval = 100)
 
FromYear  = input(defval = 2020, title = "バックテスト期間開始(年)", minval = 2010)
FromMonth = input(defval = 1, title = "バックテスト期間開始(月)", minval = 1)
FromDay   = input(defval = 1, title = "バックテスト期間開始(日)", minval = 1)
ToYear    = input(defval = 2021, title = "バックテスト期間終了(年)", minval = 2100)
ToMonth   = input(defval = 12, title = "バックテスト期間終了(月)", minval = 12)
ToDay     = input(defval = 31, title = "バックテスト期間終了(日)", minval = 31)

FromDate = timestamp("GMT+9",FromYear,FromMonth,FromDay, 0, 1)
ToDate = timestamp("GMT+9",ToYear,ToMonth,ToDay, 0, 1)

BGColor =  (time >= FromDate) and (time <= ToDate) ? #FFFF4D : na
bgcolor(BGColor, transp=94)
BackTest() =>
    time >= FromDate and time <= ToDate ? true : false
    
Up=hl2-(Factor*atr(Pd))
Dn=hl2+(Factor*atr(Pd))
MUp=security(tickerid,res,hl2-(Factor*atr(Pd)))
MDn=security(tickerid,res,hl2+(Factor*atr(Pd)))
 
Mclose=security(tickerid,res,close)
 
TrendUp=close[1]>TrendUp[1]? max(Up,TrendUp[1]) : Up
TrendDown=close[1]<TrendDown[1]? min(Dn,TrendDown[1]) : Dn
 
MTrendUp=Mclose[1]>MTrendUp[1]? max(MUp,MTrendUp[1]) : MUp
MTrendDown=Mclose[1]<MTrendDown[1]? min(MDn,MTrendDown[1]) : MDn
 
Trend = close > TrendDown[1] ? 1: close< TrendUp[1]? -1: nz(Trend[1],1)
Tsl = Trend==1? TrendUp: TrendDown
 
MTrend = Mclose > MTrendDown[1] ? 1: Mclose< MTrendUp[1]? -1: nz(MTrend[1],1)
MTsl = MTrend==1? MTrendUp: MTrendDown
 
linecolor = Trend == 1 ? green : red
plot(Tsl, color = linecolor , style = line , linewidth = 2,title = "SuperTrend")
 
Mlinecolor = MTrend == 1 ? blue : orange
plot(MTsl, color = Mlinecolor , style = line , linewidth = 2,title = "Main SuperTrend")
 
plotshape(cross(close,Tsl) and close>Tsl , "Up Arrow", shape.triangleup,location.belowbar,green,0,0)
plotshape(cross(Tsl,close) and close<Tsl , "Down Arrow", shape.triangledown , location.abovebar, red,0,0)
 
up = Trend == 1 and Trend[1] == -1 and MTrend == 1
down = Trend == -1 and Trend[1] == 1 and MTrend == -1
plotarrow(up ? Trend : na, title="Up Entry Arrow", colorup=lime, maxheight=60, minheight=50, transp=0)
plotarrow(down ? Trend : na, title="Down Entry Arrow", colordown=red, maxheight=60, minheight=50, transp=0)
 
 
golong = Trend == 1 and Trend[1] == -1 and MTrend == 1
goshort = Trend == -1 and Trend[1] == 1 and MTrend == -1

golong2 = cross(close,Tsl) and close>Tsl
goshort2 = cross(Tsl,close) and close<Tsl

if BackTest()
    strategy.entry("Buy", strategy.long,when=golong or golong2)
    strategy.close("Buy",when=goshort or goshort2)
    strategy.entry("Sell", strategy.short,when=goshort or goshort2)
    strategy.close("Sell",when=golong or golong2)

//END
